framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            cache.app.redis_cache:
                adapter: cache.app
                public: true
                default_lifetime: 3600
